name: WorkFlow
on: 
  push:
    branches:
      - feature-ariel-marihuen

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with: 
        java-version: '17'
        distribution: 'adopt'
  
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_GH }}
    - name: List directory contents 
      run: ls -l

  sast:
    runs-on: ubuntu-latest
    needs: Build
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  

      - name: Install dependencies with Yarn
        run: yarn install 

      - name: Navigate to project directory
        run: ls /home/runner/work/Laboratorio-final/Laboratorio-final


      - name: Build project
        run: yarn run build 

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          TOKEN_GH: ${{ secrets.TOKEN_GH }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args: >
            -Dsonar.projectKey=ArielAndresMarihuenMatus_Laboratorio-final
            -Dsonar.organization=devsecopsarielmarihuen
            -Dsonar.sources=.  
            -Dsonar.exclusions=**/node_modules/**

      - name: Check Quality Gate Status
        run: |
          echo "Checking Quality Gate status"
          SONAR_STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=ArielAndresMarihuenMatus_Laboratorio-final" | jq -r .projectStatus.status)
          if [ "$SONAR_STATUS" != "OK" ]; then
            echo "Quality Gate failed: $SONAR_STATUS"
            exit 1
          else
            echo "Quality Gate passed: $SONAR_STATUS"
          fi
        env:
          TOKEN_GH: ${{ secrets.TOKEN_GH }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}